services:
  pfsense-cli:
    build: .
    container_name: pfsense-cli
    env_file:
      - .env
    ports:
      - "5431:5431"  # frontend
      - "5432:5432"  # backend
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
